Example using a blend of hard type metadata and dicts for adding new …
JuliaRobotics/DistributedFactorGraphs.jl pull request #158
Opened 2019-10-14 03:43 UTC by GearsAD

…estimates

2019-10-14 03:49 UTC, dehann approved these changes

2019-10-14 03:49 UTC, dehann commented
Looks good to me!

2019-10-14 03:50 UTC, dehann commented
part of #147 discussion

2019-10-14 03:50 UTC, dehann commented
want to make sure @Affie is happy before we merge the twig, and then to master

2019-10-14 08:04 UTC, Affie commented
You can go ahead, I'm not an expert when it comes to julia.
The only thing I've found with types represented as dictionaries is its harder to use. 
Also please define the fields somehow (maybe in documentation), so I know for example :max will be there and the name won't change to something else. eg. :maximum

2019-10-14 13:01 UTC, dehann commented
unlikely to have a name change from (eg :max to :maximum), but if it does occur we will do so with deprecation cycle and minor version numbers.

2019-10-14 15:03 UTC, Affie reviewed
Maybe just hold off on it not to break IIF and first do the branch. and this for v0.5.0

2019-10-14 22:28 UTC, dehann commented
TLDR; hold off on merging this until we have spoken again please.

hi @GearsAD , Johan convinced me on using `Dict{Symbol, <: AnAbstractType}` given new and improved type inference with anonymous static parameters. https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/148#issuecomment-541536774

So shall we change that now or later?  I told Johan later, but I thought this was already merged.  Perhaps we can just do it now before merging this.  #148 already has it the way Johan suggested, we can maybe just introduce the name change to `PointParametericEstimate` etc.

2019-10-23 20:15 UTC, dehann requested changes

2019-10-23 20:15 UTC, dehann commented on src/entities/DFGVariable.jl
> +    estimateDict::Dict{Symbol, PointParametricEstimates}
`estimateDict::Dict{Symbol, <: AbstractPointParametric}`

or whatever the chosen name for `AbstractPointParametric` is in the end

2019-10-23 20:15 UTC, dehann commented on src/entities/DFGVariable.jl
> +struct PointParametricEstimates
`struct PointParametricEstimates <: AbstractPointParametric` as originally suggested by @Affie.

or whatever the chosen name for `AbstractPointParametric` is in the end

2019-10-23 20:18 UTC, dehann commented on src/entities/DFGVariable.jl
> +    estimateDict::Dict{Symbol, PointParametricEstimates}
from #148 

`<: AbstractVariableEstimate`

2019-10-23 20:18 UTC, dehann commented on src/entities/DFGVariable.jl
> +struct PointParametricEstimates
from #148

`<: AbstractVariableEstimate`

2019-10-25 09:00 UTC, Affie commented
Closed by design decision from #147 [last few comments](https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/issues/147#issuecomment-542091523)

2019-10-25 09:00 UTC, closed without merging